{{- if not .Values.secret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "passbolt-operator.secret.name" . }}
  labels:
    {{- include "passbolt-operator.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.secret.passbolt.url | b64enc }}
  gpg_key: {{ .Values.secret.passbolt.gpgKey | b64enc }}
  password: {{ .Values.secret.passbolt.password | b64enc }}
{{- end }}