project_name: passbolt-operator

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: controller
    main: main.go
    binary: controller
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - ppc64le
    goarm:
      - 7
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
    ldflags:
      - >-
        -X github.com/helm/chart-releaser/cr/cmd.Version={{ .Tag }}
        -X github.com/helm/chart-releaser/cr/cmd.GitCommit={{ .Commit }}
        -X github.com/helm/chart-releaser/cr/cmd.BuildDate={{ .Date }}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE
      - README.md

dockers:
  - goos: linux
    goarch: amd64
    skip_push: false
    dockerfile: Dockerfile
    use: buildx
    image_templates:
    - "ghcr.io/leonsteinhaeuser/passbolt-operator:{{.Tag}}-amd64"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}{{ end }}-amd64"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}{{ end }}-amd64"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:latest{{ end }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - --label=org.label-schema.schema-version=1.0
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.description='The passbolt-operator is a Kubernetes operator for syncing Passbolt secrets with Kubernetes secrets.'
      - --label=org.label-schema.vendor=Helm

  - goos: linux
    goarch: arm64
    skip_push: false
    dockerfile: Dockerfile
    use: buildx
    image_templates:
    - "ghcr.io/leonsteinhaeuser/passbolt-operator:{{.Tag}}-arm64"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}{{ end }}-arm64"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}{{ end }}-arm64"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:latest{{ end }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - --label=org.label-schema.schema-version=1.0
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.description='The passbolt-operator is a Kubernetes operator for syncing Passbolt secrets with Kubernetes secrets.'
      - --label=org.label-schema.vendor=Helm

  - goos: linux
    goarch: arm
    goarm: 7
    skip_push: false
    dockerfile: Dockerfile
    use: buildx
    image_templates:
    - "ghcr.io/leonsteinhaeuser/passbolt-operator:{{.Tag}}-arm"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}{{ end }}-arm"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}{{ end }}-arm"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:latest{{ end }}-arm"
    build_flag_templates:
      - "--platform=linux/arm"
      - --label=org.label-schema.schema-version=1.0
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.description='The passbolt-operator is a Kubernetes operator for syncing Passbolt secrets with Kubernetes secrets.'
      - --label=org.label-schema.vendor=Helm

  - goos: linux
    goarch: s390x
    skip_push: false
    dockerfile: Dockerfile
    use: buildx
    image_templates:
    - "ghcr.io/leonsteinhaeuser/passbolt-operator:{{.Tag}}-s390x"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}{{ end }}-s390x"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}{{ end }}-s390x"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:latest{{ end }}-s390x"
    build_flag_templates:
      - "--platform=linux/s390x"
      - --label=org.label-schema.schema-version=1.0
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.description='The passbolt-operator is a Kubernetes operator for syncing Passbolt secrets with Kubernetes secrets.'
      - --label=org.label-schema.vendor=Helm

  - goos: linux
    goarch: ppc64le
    skip_push: false
    dockerfile: Dockerfile
    use: buildx
    image_templates:
    - "ghcr.io/leonsteinhaeuser/passbolt-operator:{{.Tag}}-ppc64le"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}{{ end }}-ppc64le"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}{{ end }}-ppc64le"
    - "{{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:latest{{ end }}-ppc64le"
    build_flag_templates:
      - "--platform=linux/ppc64le"
      - --label=org.label-schema.schema-version=1.0
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.description='The passbolt-operator is a Kubernetes operator for syncing Passbolt secrets with Kubernetes secrets.'
      - --label=org.label-schema.vendor=Helm

docker_manifests:
  - name_template: ghcr.io/leonsteinhaeuser/passbolt-operator:{{ .Tag }}
    image_templates:
      - ghcr.io/leonsteinhaeuser/passbolt-operator:{{ .Tag }}-amd64
      - ghcr.io/leonsteinhaeuser/passbolt-operator:{{ .Tag }}-arm64
      - ghcr.io/leonsteinhaeuser/passbolt-operator:{{ .Tag }}-armv7
      - ghcr.io/leonsteinhaeuser/passbolt-operator:{{ .Tag }}-s390x
      - ghcr.io/leonsteinhaeuser/passbolt-operator:{{ .Tag }}-ppc64le
  - name_template: ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}
    image_templates:
      - ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}-amd64
      - ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}-arm64
      - ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}-armv7
      - ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}-s390x
      - ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}-ppc64le
  - name_template: ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}-arm64
      - ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}-armv7
      - ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}-s390x
      - ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}-ppc64le
  - name_template: ghcr.io/leonsteinhaeuser/passbolt-operator:latest
    image_templates:
      - ghcr.io/leonsteinhaeuser/passbolt-operator:latest-amd64
      - ghcr.io/leonsteinhaeuser/passbolt-operator:latest-arm64
      - ghcr.io/leonsteinhaeuser/passbolt-operator:latest-armv7
      - ghcr.io/leonsteinhaeuser/passbolt-operator:latest-s390x
      - ghcr.io/leonsteinhaeuser/passbolt-operator:latest-ppc64le

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snap"

release:
  draft: false
  discussion_category_name: General
  prerelease: auto
  mode: append
  header: |
    ## Release {{ .Version }} [{{ .Date }}]
  footer: |
    ## Docker Images

    amd64:

    - ghcr.io/leonsteinhaeuser/passbolt-operator:{{.Tag}}
    - {{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}{{ end }}
    - {{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:v{{ .Major }}.{{ .Minor }}{{ end }}
    - {{ if not .Prerelease }}ghcr.io/leonsteinhaeuser/passbolt-operator:latest{{ end }}
  extra_files:
    - glob: LICENSE
    - glob: README.md

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Enhancements"
      regexp: "^.*enhancement[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^github:"
      - "^ci:"
      - "^cd:"
      - "^ci/cd:"
      - "^example:"
      - "^gomod:"
      - "^git:"
      - "^goreleaser:"
      - "^Merge branch"
      - "WIP"

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
