apiVersion: passbolt.tagesspiegel.de/v1alpha2
kind: PassboltSecret
metadata:
  labels:
    app.kubernetes.io/name: passboltsecret-sample-v1alpha2
    app.kubernetes.io/instance: passboltsecret-sample-v1alpha2
    app.kubernetes.io/part-of: kubernetes-passbolt-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-passbolt-operator
  name: passboltsecret-sample-v1alpha2-dockerconfigjson
spec:
  leaveOnDelete: false
  secretType: kubernetes.io/dockerconfigjson
  passboltSecretName: APP_EXAMPLE
