apiVersion: passbolt.tagesspiegel.de/v1alpha3
kind: PassboltSecret
metadata:
  labels:
    app.kubernetes.io/name: passboltsecret
    app.kubernetes.io/instance: passboltsecret-sample
    app.kubernetes.io/part-of: passbolt-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: passbolt-operator
  name: passboltsecret-sample-v1alpha3
spec:
  leaveOnDelete: false
  secretType: Opaque
  passboltSecrets:
    s3_access_key:
      id: 184734ea-8be3-4f5a-ba6c-5f4b3c0603e8
      field: username
    s3_secret_key:
      id: 184734ea-8be3-4f5a-ba6c-5f4b3c0603e8
      field: password
    s3_endpoint:
      id: 184734ea-8be3-4f5a-ba6c-5f4b3c0603e8
      field: uri
    dsn:
      id: 184734ea-8be3-4f5a-ba6c-5f4b3c0603e8
      value: postgres://{{.Username}}@{{.URI}}/passbolt?sslmode=disable&password={{.Password}}&connect_timeout=10
  plainTextFields:
    key: value
    foo: bar
