apiVersion: passbolt.tagesspiegel.de/v1alpha3
kind: PassboltSecret
metadata:
  labels:
    app.kubernetes.io/name: passboltsecret
    app.kubernetes.io/instance: passboltsecret-sample
    app.kubernetes.io/part-of: passbolt-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: passbolt-operator
  name: passboltsecret-sample
spec:
  leaveOnDelete: false
  secretType: Opaque
  passboltSecrets:
    s3_access_key:
      name: APP_EXAMPLE
      field: username
    s3_secret_key:
      name: APP_EXAMPLE
      field: password
    s3_endpoint:
      name: APP_EXAMPLE
      field: uri
    dsn:
      name: APP_EXAMPLE
      value: postgres://{{.Username}}@{{.URI}}/passbolt?sslmode=disable&password={{.Password}}&connect_timeout=10
  plainTextFields:
    key: value
    foo: bar
